In [1]:
import pandas as pd
import numpy as np
##import matplotlib.pyplot as plt
##import seaborn as sns

In [2]:
data = pd.read_csv("IRIS.csv")
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [3]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
len(x)

150

In [5]:
print(y)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [6]:
len(y)

150

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test= train_test_split(x , y, test_size =0.2 , random_state=21)


In [ ]:
print(x_train)

[[4.5 2.3 1.3 0.3]
 [7.9 3.8 6.4 2. ]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.6 0.2]
 [6.2 2.8 4.8 1.8]
 [6.5 2.8 4.6 1.5]
 [6.  3.4 4.5 1.6]
 [5.8 2.8 5.1 2.4]
 [4.4 3.  1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [5.9 3.  5.1 1.8]
 [6.3 3.4 5.6 2.4]
 [5.7 2.5 5.  2. ]
 [6.2 2.9 4.3 1.3]
 [6.9 3.1 5.1 2.3]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.3 3.  1.1 0.1]
 [6.2 2.2 4.5 1.5]
 [4.8 3.4 1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [5.  3.3 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [7.7 2.6 6.9 2.3]
 [5.7 2.8 4.5 1.3]
 [5.8 2.7 4.1 1. ]
 [4.6 3.1 1.5 0.2]
 [5.1 3.5 1.4 0.3]
 [7.7 3.  6.1 2.3]
 [4.7 3.2 1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [5.7 2.9 4.2 1.3]
 [5.5 2.5 4.  1.3]
 [5.2 3.5 1.5 0.2]
 [6.7 2.5 5.8 1.8]
 [6.4 3.2 4.5 1.5]
 [4.9 3.  1.4 0.2]
 [5.4 3.9 1.3 0.4]
 [4.9 2.5 4.5 1.7]
 [6.7 3.1 4.7 1.5]
 [4.9 3.1 1.5 0.1]
 [6.5 3.  5.8 2.2]
 [5.  2.3 3.3 1. ]
 [6.1 2.6 5.6 1.4]
 [5.  3.5 1.6 0.6]
 [6.4 2.7 5.3 1.9]
 [5.1 3.4 1.5 0.2]
 [4.6 3.2 1.4 0.2]
 [6.  2.9 4.5 1.5]
 [6.5 3.  5.

In [ ]:
len(x_train)

In [ ]:
print(x_test)

In [ ]:
print(y_test)

In [9]:
from sklearn.tree import DecisionTreeClassifier
dtc= DecisionTreeClassifier(criterion = "entropy" ,random_state =21)

In [10]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=21)

In [11]:
y_pred =dtc.predict(x_test)
print(y_pred)

['versicolor' 'setosa' 'setosa' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'virginica' 'setosa' 'setosa' 'versicolor' 'versicolor'
 'virginica' 'virginica' 'setosa' 'virginica' 'virginica' 'versicolor'
 'setosa' 'virginica' 'virginica' 'versicolor' 'virginica' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'setosa' 'versicolor' 'virginica']


In [19]:
from sklearn import metrics
print('Accuracy of the Classifier is:' , metrics.accuracy_score(y_test, y_pred)*100)

Accuracy of the Classifier is: 93.33333333333333


In [25]:
import time
start_time = time.time()
dtc.fit(x_train, y_train)
predict_time = time.time() - start_time
print("Time Taken by the model to train is", + predict_time)

Time Taken by the model to train is 0.002762317657470703


In [26]:
stat_time = time.time()
pred_time = dtc.predict(x_test)
predict_time= time.time() - start_time
print("Time Taken by the model to train is", + predict_time)

Time Taken by the model to train is 2.404104232788086
